export interface ExamLevel {
  id: string;
  name: string;
  shortName: string;
  topics: string[];
}

export interface FinancialExam {
  id: string;
  name: string;
  fullName: string;
  description: string;
  /** Default/overview topics (usually first stage) */
  topics: string[];
  logo: string;
  levels: ExamLevel[];
  /** UI label for the stage selector, e.g. "Level", "Part", "Section" */
  levelLabel: string;
}

export const FINANCIAL_EXAMS: FinancialExam[] = [
  {
    id: "cfa",
    name: "CFA",
    fullName: "Chartered Financial Analyst",
    description: "Global investment management and portfolio analysis qualification.",
    logo: "/exams/cfa.svg",
    levelLabel: "Level",
    topics: [
      "Ethical & Professional Standards",
      "Quantitative Methods",
      "Economics",
      "Financial Statement Analysis",
      "Corporate Issuers",
      "Equity Investments",
      "Fixed Income",
      "Derivatives",
      "Alternative Investments",
      "Portfolio Management",
    ],
    levels: [
      {
        id: "l1",
        name: "Level I",
        shortName: "L1",
        topics: [
          "Ethical & Professional Standards",
          "Quantitative Methods",
          "Economics",
          "Financial Statement Analysis",
          "Corporate Issuers",
          "Equity Investments",
          "Fixed Income",
          "Derivatives",
          "Alternative Investments",
          "Portfolio Management",
        ],
      },
      {
        id: "l2",
        name: "Level II",
        shortName: "L2",
        topics: [
          "Ethical & Professional Standards",
          "Quantitative Methods",
          "Economics",
          "Financial Statement Analysis",
          "Corporate Issuers",
          "Equity Valuation",
          "Fixed Income",
          "Derivatives",
          "Alternative Investments",
          "Portfolio Management",
        ],
      },
      {
        id: "l3",
        name: "Level III",
        shortName: "L3",
        topics: [
          "Ethical & Professional Standards",
          "Behavioral Finance",
          "Capital Market Expectations",
          "Asset Allocation & Related Decisions",
          "Derivatives & Currency Management",
          "Fixed-Income Portfolio Management",
          "Equity Portfolio Management",
          "Alternative Investment Portfolio Management",
          "Private Wealth Management",
          "Institutional Investors",
          "Trading, Performance Evaluation & Manager Selection",
          "Case Study / Constructed Response Practice",
        ],
      },
    ],
  },
  {
    id: "frm",
    name: "FRM",
    fullName: "Financial Risk Manager",
    description: "Risk management certification covering market, credit, and operational risk.",
    logo: "/exams/frm.svg",
    levelLabel: "Part",
    topics: [
      "Foundations of Risk Management",
      "Quantitative Analysis",
      "Financial Markets & Products",
      "Valuation & Risk Models",
    ],
    levels: [
      {
        id: "p1",
        name: "Part I",
        shortName: "P1",
        topics: [
          "Foundations — Risk types, governance & GARP Code of Conduct",
          "Foundations — Enterprise risk management & risk culture",
          "Quantitative — Probability, statistics & distributions",
          "Quantitative — Regression, forecasting & simulation",
          "Quantitative — Hypothesis testing & estimation",
          "Markets — Banks, insurers & fund structures",
          "Markets — Equities, FX, commodities & fixed income",
          "Markets — Forwards, futures, swaps & options",
          "Markets — Mortgages, securitization & credit derivatives",
          "Valuation — Bond pricing, duration & convexity",
          "Valuation — Option valuation & Greeks",
          "Valuation — VaR, expected shortfall & risk aggregation",
          "Valuation — Mapping, backtesting & model risk",
          "Valuation — Credit exposure & counterparty risk basics",
        ],
      },
      {
        id: "p2",
        name: "Part II",
        shortName: "P2",
        topics: [
          "Market Risk — VaR, ES & parametric/historical/Monte Carlo methods",
          "Market Risk — Volatility, correlation & nonlinear risk",
          "Market Risk — Risk capital & model validation",
          "Credit Risk — Default risk, ratings & credit scoring",
          "Credit Risk — Credit VaR, portfolio credit risk & securitization",
          "Credit Risk — Counterparty risk, CVA & wrong-way risk",
          "Operational Risk — Risk taxonomy, loss data & capital",
          "Operational Risk — Resilience, cyber & conduct risk",
          "Liquidity & Treasury — Funding liquidity & LCR/NSFR concepts",
          "Liquidity & Treasury — Asset liquidity & stress testing",
          "Investment Risk — Hedge funds, private equity & risk budgeting",
          "Investment Risk — Risk-adjusted performance & portfolio construction",
          "Current Issues — Macro, regulation & market structure themes",
        ],
      },
    ],
  },
  {
    id: "cpa",
    name: "CPA",
    fullName: "Certified Public Accountant",
    description: "Professional accounting credential covering audit, tax, and financial reporting.",
    logo: "/exams/cpa.svg",
    levelLabel: "Section",
    topics: [
      "Auditing & Attestation (AUD)",
      "Financial Accounting & Reporting (FAR)",
      "Taxation & Regulation (REG)",
      "Discipline section (BAR / ISC / TCP)",
    ],
    levels: [
      {
        id: "aud",
        name: "AUD — Auditing & Attestation",
        shortName: "AUD",
        topics: [
          "Ethics, independence & professional responsibilities",
          "Terms of engagement & planning an audit",
          "Internal control & COSO / IT general controls",
          "Risk assessment & materiality",
          "Obtaining audit evidence & sampling",
          "Tests of controls & substantive procedures",
          "Audit conclusions, subsequent events & reports",
          "Other assurance & attestation engagements",
        ],
      },
      {
        id: "far",
        name: "FAR — Financial Accounting & Reporting",
        shortName: "FAR",
        topics: [
          "Conceptual framework & financial reporting standards",
          "Income statement, balance sheet & cash flows",
          "Revenue recognition & leases",
          "Investments, business combinations & consolidations",
          "Pensions, contingencies & fair value",
          "Debt, equity & EPS",
          "Temporary differences & income taxes",
          "State & local government accounting (GASB)",
        ],
      },
      {
        id: "reg",
        name: "REG — Taxation & Regulation",
        shortName: "REG",
        topics: [
          "Ethics, tax procedures & taxpayer penalties",
          "Business law — contracts, agency & debtor-creditor",
          "Business structure — partnerships, corporations & LLCs",
          "Federal taxation of property transactions",
          "Individual taxation — gross income & deductions",
          "Individual taxation — credits, AMT & filing",
          "Entity taxation — C-corps, S-corps & partnerships",
          "Tax-exempt organizations & estate/gift tax basics",
        ],
      },
      {
        id: "discipline",
        name: "Discipline (BAR / ISC / TCP)",
        shortName: "Discipline",
        topics: [
          "BAR — Business analysis & financial statement analysis",
          "BAR — Technical accounting & reporting applications",
          "BAR — State & local governments (advanced)",
          "ISC — IT governance, SOC reports & security",
          "ISC — Business processes, data & controls",
          "ISC — Information system audits",
          "TCP — Personal financial planning & tax compliance",
          "TCP — Entity tax compliance & planning",
          "TCP — Property transactions & advanced tax topics",
        ],
      },
    ],
  },
  {
    id: "acca",
    name: "ACCA",
    fullName: "Association of Chartered Certified Accountants",
    description: "International accounting and finance qualification with broad business coverage.",
    logo: "/exams/acca.svg",
    levelLabel: "Stage",
    topics: [
      "BT — Business & Technology",
      "MA — Management Accounting",
      "FA — Financial Accounting",
      "LW — Corporate & Business Law",
      "PM — Performance Management",
      "TX — Taxation",
      "FR — Financial Reporting",
      "AA — Audit & Assurance",
      "FM — Financial Management",
      "SBL — Strategic Business Leader",
      "SBR — Strategic Business Reporting",
      "AFM — Advanced Financial Management",
      "APM — Advanced Performance Management",
      "ATX — Advanced Taxation",
      "AAA — Advanced Audit & Assurance",
      "EPSM — Ethics & Professional Skills Module",
    ],
    levels: [
      {
        id: "all",
        name: "Full qualification (all 13 papers + EPSM)",
        shortName: "All papers",
        topics: [
          "BT — Business & Technology (Applied Knowledge)",
          "MA — Management Accounting (Applied Knowledge)",
          "FA — Financial Accounting (Applied Knowledge)",
          "LW — Corporate & Business Law (Applied Skills)",
          "PM — Performance Management (Applied Skills)",
          "TX — Taxation (Applied Skills)",
          "FR — Financial Reporting (Applied Skills)",
          "AA — Audit & Assurance (Applied Skills)",
          "FM — Financial Management (Applied Skills)",
          "SBL — Strategic Business Leader (Essential)",
          "SBR — Strategic Business Reporting (Essential)",
          "AFM — Advanced Financial Management (Option)",
          "APM — Advanced Performance Management (Option)",
          "ATX — Advanced Taxation (Option)",
          "AAA — Advanced Audit & Assurance (Option)",
          "EPSM — Ethics & Professional Skills Module",
        ],
      },
      {
        id: "applied-knowledge",
        name: "Applied Knowledge",
        shortName: "Knowledge",
        topics: [
          "BT — Business organisation structure, governance & management",
          "BT — Environmental influences, markets & competitive factors",
          "BT — Accounting & reporting systems, controls & compliance",
          "BT — Personal effectiveness, communication & ethics",
          "MA — Cost accounting techniques & cost classification",
          "MA — Budgeting, forecasting & standard costing",
          "MA — Performance measurement & monitoring",
          "MA — Short-term decision-making techniques",
          "FA — Double-entry bookkeeping & accounting equation",
          "FA — Trial balance, adjustments & errors",
          "FA — Preparing financial statements for sole traders & companies",
          "FA — Interpretation of financial statements",
        ],
      },
      {
        id: "applied-skills",
        name: "Applied Skills",
        shortName: "Skills",
        topics: [
          "LW — Essential elements of legal systems & business organisations",
          "LW — Contract, employment & tort law",
          "LW — Company law — formation, capital, directors & insolvency",
          "PM — Specialist cost & management accounting techniques",
          "PM — Decision-making techniques & risk/uncertainty",
          "PM — Budgeting, standard costing & variance analysis",
          "PM — Performance analysis & divisional performance",
          "TX — UK tax system, income tax & NIC (or variant syllabus)",
          "TX — Corporation tax & chargeable gains",
          "TX — Inheritance tax, VAT & tax administration",
          "FR — Conceptual framework & regulatory framework",
          "FR — Single-entity financial statements (IFRS)",
          "FR — Business combinations & consolidated financial statements",
          "FR — Interpretation & analysis of financial statements",
          "AA — Audit framework, ethics & regulation",
          "AA — Planning, risk assessment & internal control",
          "AA — Audit evidence, procedures & sampling",
          "AA — Review, reports & assurance engagements",
          "FM — Financial management function & environment",
          "FM — Working capital management",
          "FM — Investment appraisal & business finance",
          "FM — Business valuations, risk management & FX/interest risk",
        ],
      },
      {
        id: "strategic-professional",
        name: "Strategic Professional",
        shortName: "Strategic",
        topics: [
          "SBL — Leadership, governance & stakeholder management (Essential)",
          "SBL — Strategy, innovation, data & technology (Essential)",
          "SBL — Risk, control, finance & professional skills (Essential)",
          "SBR — Financial reporting framework & reporting performance (Essential)",
          "SBR — Group reporting & changes in group structure (Essential)",
          "SBR — Current issues & ethical/professional issues (Essential)",
          "AFM — Advanced investment appraisal & cost of capital (Option)",
          "AFM — Acquisitions, reconstructions & treasury/FX risk (Option)",
          "APM — Strategic performance management systems (Option)",
          "APM — Performance evaluation, change & HR issues (Option)",
          "ATX — Advanced corporation/personal tax planning (Option)",
          "ATX — International tax & tax of business combinations (Option)",
          "AAA — Advanced audit planning, evidence & reporting (Option)",
          "AAA — Other assignments, current issues & ethics (Option)",
          "EPSM — Ethics & Professional Skills Module (required)",
        ],
      },
    ],
  },
  {
    id: "caia",
    name: "CAIA",
    fullName: "Chartered Alternative Investment Analyst",
    description: "Specialist credential for hedge funds, private equity, and alternative assets.",
    logo: "/exams/caia.svg",
    levelLabel: "Level",
    topics: [
      "Professional Standards & Ethics",
      "Introduction to Alternative Investments",
      "Real Assets",
      "Private Equity",
      "Hedge Funds",
      "Structured Products",
    ],
    levels: [
      {
        id: "l1",
        name: "Level I",
        shortName: "L1",
        topics: [
          "Professional Standards & Ethics",
          "Introduction to Alternative Investments",
          "Real Assets — real estate, infrastructure, natural resources",
          "Private Equity — venture capital & buyouts",
          "Private Debt & Direct Lending",
          "Hedge Funds — strategies & structures",
          "Digital Assets & crypto markets",
          "Structured Products — MBS, ABS & credit structures",
          "Risk & return measures for alternatives",
          "Due diligence foundations",
        ],
      },
      {
        id: "l2",
        name: "Level II",
        shortName: "L2",
        topics: [
          "Professional Standards & Ethics (applied)",
          "Institutional investors & asset owner objectives",
          "Private equity & real assets — advanced applications",
          "Hedge fund strategies — advanced applications",
          "Structured products & credit strategies",
          "Asset allocation with alternatives",
          "Portfolio construction & risk budgeting",
          "Liquidity, valuation & operational risk",
          "Manager selection & due diligence",
          "Monitoring, reporting & governance",
        ],
      },
    ],
  },
  {
    id: "cfp",
    name: "CFP",
    fullName: "Certified Financial Planner",
    description: "Personal financial planning certification for wealth and retirement planning.",
    logo: "/exams/cfp.svg",
    levelLabel: "Exam",
    topics: [
      "Professional Conduct & Regulation",
      "General Principles of Financial Planning",
      "Risk Management & Insurance Planning",
      "Investment Planning",
      "Tax Planning",
      "Retirement Savings & Income Planning",
      "Estate Planning",
      "Psychology of Financial Planning",
    ],
    levels: [
      {
        id: "full",
        name: "CFP Certification Exam",
        shortName: "Exam",
        topics: [
          "Professional Conduct & Regulation / CFP Board Code & Standards",
          "Financial planning process & client engagement",
          "Cash flow, education funding & debt management",
          "Risk management & insurance planning",
          "Investment products, portfolio theory & asset allocation",
          "Tax planning for individuals & investments",
          "Retirement savings vehicles & income strategies",
          "Social Security / pensions & longevity planning",
          "Estate planning documents, trusts & wealth transfer",
          "Behavioral finance & psychology of financial planning",
        ],
      },
    ],
  },
  {
    id: "sie",
    name: "SIE",
    fullName: "Securities Industry Essentials",
    description: "Entry-level securities industry exam covering products, regulations, and practices.",
    logo: "/exams/sie.svg",
    levelLabel: "Exam",
    topics: [
      "Knowledge of Capital Markets",
      "Understanding Products & Their Risks",
      "Understanding Trading, Customer Accounts & Prohibited Activities",
      "Overview of the Regulatory Framework",
    ],
    levels: [
      {
        id: "full",
        name: "SIE Exam",
        shortName: "SIE",
        topics: [
          "Capital markets structure — issuers, investors & intermediaries",
          "Economic factors & offering process (IPOs, private placements)",
          "Equity & debt securities characteristics",
          "Packaged products — mutual funds, ETFs, UITs, variable contracts",
          "Options, municipal securities & other products (overview)",
          "Trading markets, orders & settlement concepts",
          "Customer accounts, account types & account registration",
          "Prohibited activities — manipulation, insider trading & fraud",
          "Regulatory framework — SEC, SROs, FINRA & MSRB roles",
          "Employee conduct, registration & continuing education basics",
        ],
      },
    ],
  },
  {
    id: "cima",
    name: "CIMA",
    fullName: "Chartered Institute of Management Accountants",
    description: "Management accounting and strategic business leadership qualification.",
    logo: "/exams/cima.svg",
    levelLabel: "Level",
    topics: [
      "BA1–BA4 Certificate in Business Accounting",
      "E1 / P1 / F1 Operational Level + Case Study",
      "E2 / P2 / F2 Management Level + Case Study",
      "E3 / P3 / F3 Strategic Level + Case Study",
    ],
    levels: [
      {
        id: "certificate",
        name: "Certificate in Business Accounting",
        shortName: "Certificate",
        topics: [
          "BA1 — Macroeconomic & microeconomic environment",
          "BA1 — Financial markets & data analysis for business",
          "BA2 — Costing, budgeting & decision making",
          "BA2 — Short-term finance & working capital",
          "BA3 — Double entry, ledgers & trial balance",
          "BA3 — Financial statements preparation & interpretation",
          "BA4 — Ethics, corporate governance & CSR",
          "BA4 — Business law — contracts, employment & companies",
        ],
      },
      {
        id: "operational",
        name: "Operational Level",
        shortName: "Operational",
        topics: [
          "E1 — Role of the finance function & digital world",
          "E1 — Technology, data & operations management",
          "P1 — Cost accounting & decision making",
          "P1 — Budgeting, forecasting & performance measures",
          "F1 — Financial reporting & taxation basics",
          "F1 — Working capital & short-term finance",
          "Operational Case Study — integrated application",
        ],
      },
      {
        id: "management",
        name: "Management Level",
        shortName: "Management",
        topics: [
          "E2 — Business models, project & relationship management",
          "E2 — Managing people & organisational change",
          "P2 — Advanced costing, pricing & risk",
          "P2 — Managing performance of organisational units",
          "F2 — Group accounting & advanced financial reporting",
          "F2 — Financing decisions & financial analysis",
          "Management Case Study — integrated application",
        ],
      },
      {
        id: "strategic",
        name: "Strategic Level",
        shortName: "Strategic",
        topics: [
          "E3 — Strategic analysis, choice & implementation",
          "E3 — Digital strategy & organisational ecosystems",
          "P3 — Enterprise risk management & internal control",
          "P3 — Governance, ethics & strategic performance",
          "F3 — Financial strategy, valuation & M&A",
          "F3 — Advanced treasury & risk financing",
          "Strategic Case Study — integrated application",
        ],
      },
    ],
  },
  {
    id: "cmt",
    name: "CMT",
    fullName: "Chartered Market Technician",
    description: "Technical analysis credential for market timing and chart-based investing.",
    logo: "/exams/cmt.svg",
    levelLabel: "Level",
    topics: [
      "Theory & History of Technical Analysis",
      "Charts & Chart Patterns",
      "Trend Analysis",
      "Technical Indicators",
      "Behavioral Finance",
    ],
    levels: [
      {
        id: "l1",
        name: "Level I",
        shortName: "L1",
        topics: [
          "Theory & history of technical analysis",
          "Dow Theory & classical market concepts",
          "Chart construction — bar, line, candlestick & point-and-figure",
          "Trend, support/resistance & chart patterns",
          "Candlestick patterns & confirmation",
          "Moving averages, oscillators & momentum",
          "Volume, breadth & sentiment indicators",
          "Cycles & seasonality (introduction)",
          "Behavioral finance foundations for technicians",
        ],
      },
      {
        id: "l2",
        name: "Level II",
        shortName: "L2",
        topics: [
          "Advanced pattern recognition & multi-timeframe analysis",
          "Statistical & quantitative methods for technicians",
          "Volatility measures & market intermarket analysis",
          "Relative strength & sector/asset rotation",
          "Portfolio applications of technical analysis",
          "Risk management rules for technical strategies",
          "System design concepts & objectivity",
          "Ethics for CMT candidates",
        ],
      },
      {
        id: "l3",
        name: "Level III",
        shortName: "L3",
        topics: [
          "Integrating technical analysis into investment process",
          "Advanced money management & position sizing",
          "Developing, testing & implementing trading systems",
          "Performance measurement of technical strategies",
          "Communicating technical views to clients/PMs",
          "Ethics & professional practice (essay/application)",
          "Case-based constructed-response practice",
        ],
      },
    ],
  },
  {
    id: "cfa-esg",
    name: "CFA ESG",
    fullName: "CFA Certificate in ESG Investing",
    description: "ESG integration, climate risk, and sustainable investment analysis.",
    logo: "/exams/cfa-esg.svg",
    levelLabel: "Exam",
    topics: [
      "Introduction to ESG Investing",
      "The ESG Market",
      "Environmental Factors",
      "Social Factors",
      "Governance Factors",
      "Engagement & Stewardship",
      "ESG Analysis, Valuation & Integration",
      "ESG Integrated Portfolio Construction & Management",
      "Investment Mandates, Portfolio Analytics & Client Reporting",
    ],
    levels: [
      {
        id: "full",
        name: "Certificate Exam",
        shortName: "Certificate",
        topics: [
          "Introduction to ESG investing & responsible investment approaches",
          "The ESG market — investors, products & regulation landscape",
          "Environmental factors — climate, natural capital & transition risk",
          "Social factors — human capital, rights & community impacts",
          "Governance factors — boards, ownership & corporate behaviour",
          "Engagement & stewardship — voting, dialogue & escalation",
          "ESG analysis, materiality, valuation & integration techniques",
          "ESG-integrated portfolio construction, screening & optimisation",
          "Investment mandates, portfolio analytics & client reporting",
        ],
      },
    ],
  },
];

export function getExamById(id: string): FinancialExam | undefined {
  return FINANCIAL_EXAMS.find((exam) => exam.id === id);
}

export function getExamLevel(examId: string, levelId: string): ExamLevel | undefined {
  const exam = getExamById(examId);
  return exam?.levels.find((l) => l.id === levelId);
}

export function getDefaultLevelId(examId: string): string {
  const exam = getExamById(examId);
  // Prefer full overview when available (e.g. ACCA all papers)
  if (exam?.levels.some((l) => l.id === "all")) return "all";
  return exam?.levels[0]?.id || "full";
}

export function examHasMultipleLevels(examId: string): boolean {
  const exam = getExamById(examId);
  return (exam?.levels.length || 0) > 1;
}
