import type { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { SITE_NAME, SITE_URL, TELEGRAM_CONTACT, TELEGRAM_URL } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Terms of Use | ${SITE_NAME}`,
  description: `Terms of Use for ${SITE_NAME} — AI-powered financial qualification exam tutoring.`,
};

export default function TermsPage() {
  return (
    <>
      <Header />
      <main className="mx-auto w-full max-w-3xl flex-1 px-4 py-10 sm:px-6">
        <section className="mb-10">
          <p className="text-sm font-medium text-gold">Legal</p>
          <h1 className="font-display mt-2 text-4xl font-semibold tracking-tight text-navy">
            Terms of Use
          </h1>
          <p className="mt-3 text-sm text-muted">
            Last updated: July 22, 2026 · {SITE_URL}
          </p>
        </section>

        <article className="surface-card space-y-8 p-6 text-sm leading-relaxed text-slate-700 sm:p-8">
          <div>
            <h2 className="font-display mb-2 text-lg font-semibold text-navy">1. Acceptance of Terms</h2>
            <p>
              By accessing or using {SITE_NAME} (&quot;the Service&quot;) at {SITE_URL}, you agree to be
              bound by these Terms of Use. If you do not agree to these terms, please do not use the
              Service. {SITE_NAME} is operated as an AI-powered educational tutoring platform for
              financial qualification exam preparation.
            </p>
          </div>

          <div>
            <h2 className="font-display mb-2 text-lg font-semibold text-navy">2. Description of Service</h2>
            <p>
              {SITE_NAME} provides an AI chatbot that assists users in studying for recognized financial
              qualification examinations, including but not limited to CFA, FRM, CPA, ACCA, CAIA, CFP,
              SIE, CIMA, CMT, and CFA ESG Investing. The Service uses large language models (Google
              Gemini as the default provider, and DeepSeek as an alternative — including automatic
              fallback when Gemini is unavailable, such as for users in mainland China)
              to generate educational responses related to the exam selected by the user.
            </p>
          </div>

          <div>
            <h2 className="font-display mb-2 text-lg font-semibold text-navy">3. Token System &amp; Payment</h2>
            <p>
              New accounts receive 50 free tokens upon registration. Each question submitted to the
              chatbot consumes 1 token when an answer is successfully returned. Once free tokens are
              exhausted, users may purchase monthly token plans through the website. Plans expire after{" "}
              <strong>1 month</strong> and renew automatically unless cancelled in My Profile;
              cancellation stops future renewals while membership continues until the end of the
              current cycle. A paid plan also unlocks Ask a human mentor for the active membership
              month. Payments are received via Wise Business payment links when configured (or secure
              card checkout as fallback). Tokens are non-transferable and have no cash value. We
              reserve the right to modify token pricing and free token allocations with reasonable
              notice.
            </p>
          </div>

          <div>
            <h2 className="font-display mb-2 text-lg font-semibold text-navy">4. Educational Use Only</h2>
            <p>
              The Service is intended solely for educational and study preparation purposes. Responses
              generated by the AI are for informational and learning support only and do not constitute
              professional financial, legal, tax, or investment advice. {SITE_NAME} is not affiliated
              with, endorsed by, or officially connected to any examination body or certification
              organization (including CFA Institute, GARP, AICPA, ACCA, CAIA Association, CFP Board,
              FINRA, CIMA, CMT Association, or any other credentialing body).
            </p>
          </div>

          <div>
            <h2 className="font-display mb-2 text-lg font-semibold text-navy">5. Accuracy Disclaimer</h2>
            <p>
              While we strive to provide accurate and helpful study guidance, AI-generated responses may
              contain errors, omissions, or outdated information. Users should verify important
              information against official exam materials, textbooks, and the relevant certification
              body&apos;s publications. {SITE_NAME} makes no warranties, express or implied, regarding
              the accuracy, completeness, or reliability of any content provided through the Service.
            </p>
          </div>

          <div>
            <h2 className="font-display mb-2 text-lg font-semibold text-navy">6. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="mt-2 list-disc space-y-1 pl-5 text-slate-700">
              <li>Use the Service to submit vulgar, abusive, harassing, or offensive content.</li>
              <li>Attempt to circumvent the token system or abuse free token allocations.</li>
              <li>Use automated tools, bots, or scripts to access the Service without authorization.</li>
              <li>
                Submit questions unrelated to financial qualification exam preparation after being
                redirected.
              </li>
              <li>Reverse engineer, decompile, or attempt to extract the underlying AI models or prompts.</li>
              <li>Use the Service for any unlawful purpose or in violation of applicable regulations.</li>
            </ul>
            <p className="mt-2">
              {SITE_NAME} reserves the right to gently decline irrelevant or inappropriate questions
              and may restrict access for repeated violations of these guidelines.
            </p>
          </div>

          <div>
            <h2 className="font-display mb-2 text-lg font-semibold text-navy">7. Intellectual Property</h2>
            <p>
              The {SITE_NAME} name, logo, website design, and original content are the property of{" "}
              {SITE_NAME} and are protected by applicable intellectual property laws. Exam names and
              certification marks referenced on the platform belong to their respective owners and are
              used for descriptive purposes only. You may not reproduce, distribute, or create
              derivative works from the Service without prior written consent.
            </p>
          </div>

          <div>
            <h2 className="font-display mb-2 text-lg font-semibold text-navy">8. Privacy</h2>
            <p>
              {SITE_NAME} requires an account for chatbot use and Study Path. Account details, token
              balances, study portfolios, and purchase records are stored securely on our servers. Chat
              messages are transmitted to third-party AI providers (Google and DeepSeek) for processing.
              We do not sell personal data. For questions about data handling, please contact us via our{" "}
              <Link href="/contact" className="font-medium text-navy underline underline-offset-2">
                Contact page
              </Link>
              .
            </p>
          </div>

          <div>
            <h2 className="font-display mb-2 text-lg font-semibold text-navy">9. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, {SITE_NAME} and its operators shall not be liable
              for any direct, indirect, incidental, special, consequential, or punitive damages arising
              from your use of the Service, including but not limited to exam performance outcomes,
              reliance on AI-generated content, token purchase disputes, or service interruptions. Your
              use of the Service is at your own risk.
            </p>
          </div>

          <div>
            <h2 className="font-display mb-2 text-lg font-semibold text-navy">10. Service Modifications</h2>
            <p>
              We reserve the right to modify, suspend, or discontinue the Service (or any part thereof)
              at any time without prior notice. We may update these Terms of Use periodically.
              Continued use of the Service after changes constitutes acceptance of the revised terms.
            </p>
          </div>

          <div>
            <h2 className="font-display mb-2 text-lg font-semibold text-navy">11. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of Singapore,
              without regard to conflict of law principles. Any disputes arising under these Terms shall
              be subject to the exclusive jurisdiction of the courts of Singapore.
            </p>
          </div>

          <div>
            <h2 className="font-display mb-2 text-lg font-semibold text-navy">12. Contact</h2>
            <p>
              For questions about these Terms, please visit our{" "}
              <Link href="/contact" className="font-medium text-navy underline underline-offset-2">
                Contact Us
              </Link>{" "}
              page or reach us on Telegram at{" "}
              <a
                href={TELEGRAM_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="font-medium text-navy underline underline-offset-2"
              >
                {TELEGRAM_CONTACT}
              </a>
              .
            </p>
          </div>
        </article>
      </main>
      <Footer />
    </>
  );
}
